version: "3"

services:
  server:
    build:
      context: ./
    user: "node"
    working_dir: /application
    environment:
      - NODE_ENV=development
      #- NODE_ENV=production
    ports:
      - "7778:7778"
    tty: true
